name: Issues Event
on: issues 
jobs:
    IssuesEvent:
        runs-on: ubuntu-latest
        steps: 
            - name: Output GitHub context
              run: echo "${{ toJSON(github) }}"

             